let totalOld = $('#totalOld'),
    firstOld = $('#firstOld'),
    secondOld = $('#secondOld'),
    thirdOld = $('#thirdOld'),
    totalNow = $('#totalNow'),
    firstNow = $('#firstNow'),
    secondNow = $('#secondNow'),
    thirdNow = $('#thirdNow'),
    monthKW = $('#monthKW'),
    firstKW = $('#firstKW'),
    secondKW = $('#secondKW'),
    thirdKW = $('#thirdKW'),
    totalMoney = $('#totalMoney'),
    firstMoney = $('#firstMoney'),
    secondMoney = $('#secondMoney'),
    thirdMoney = $('#thirdMoney');

